name: Build and deploy React Vite app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read
    steps:
      # Clonar el repositorio
      - uses: actions/checkout@v4

      # Configurar Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # Instalar dependencias y construir app
      - name: Install Frontend dependencies and build
        run: |
          npm ci
          npm run build

      # Copiar build al backend
      - name: Copy frontend build to backend
        run: |
          xcopy /E /I /Y dist backend\dist
    
      # Instalar dependencias del backend
      - name: Install backend dependencies
        run: |
          cd backend
          npm ci

      # Listar archivos (opcional, para debugging)
      - name: List files after build
        run: dir /s
        shell: cmd

      # Login a Azure
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_262D49CE86644C4BA057F28F66DFBC65 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_20EB930BE7014E06A6AF5EF87CBA595E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4F0028C39E684FA793AF65345998E65C }}

      # Deploy a Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'proyecto-negocio-de-superpoderes'
          slot-name: 'Production'
          package: ./backend   # apunta directamente a la carpeta de build
